_BASE_: ../Base-SBS.yml

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: logs/MarketT_Quick/Sbaseline_R50

MODEL:
  META_ARCHITECTURE: Sbaseline

  DETACH_ATTN: False # bad

  DETACH_ALL: False # bad

  LAST_EMBEDDING: False
  LAST_ONLY: False

  BACKBONE:
    WITH_IBN: True
    WITH_NL: True
    WITH_SE: False
    PRETRAIN: True
    EMBEDDING_DIM: 512 # 1024

    ATTACH_ACTIVATION: False # bad
    ATTNSHAPED_ACTIVATION: False # bad
    ADJ_KEEP: False

    NORM: BN
    # PRETRAIN_PATH: '/mnt21t/home/mm2022/fast-reid/weights/lup_moco_r50.pth'
    # PRETRAIN_PATH: '/mnt21t/home/mm2022/fast-reid/weights/lupws_r50.pth'

  LOSSES:
    NAME: ("CrossEntropyLoss","TripletLoss",)
        
  HEADS:
    NORM: BN
    ATTN: 8

INPUT:
  AUTOAUG:
    ENABLED: False

  RPT:
    ENABLED: True

  SIZE_TRAIN: [ 384, 192 ]

  SIZE_TEST: [ 384, 192 ]

SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 64

  MAX_EPOCH: 120

  # SCHED: MultiStepLR
  # STEPS: [70, 90]
  # GAMMA: 0.1
  
  # DELAY_EPOCHS: 0
  # ETA_MIN_LR: 1.0e-07
  # FREEZE_ITERS: 0

  CHECKPOINT_PERIOD: 20

  FREEZE_ITERS: 0

TEST:
  EVAL_PERIOD: 4
  IMS_PER_BATCH: 128
