_BASE_: ../Base-SBS.yml

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: logs/MarketT/Sbaseline_R50

MODEL:
  META_ARCHITECTURE: Sbaseline

  DETACH_ATTN: False

  BACKBONE:
    WITH_IBN: True
    WITH_NL: True
    PRETRAIN: True
    EMBEDDING_DIM: 512

    ATTACH_ACTIVATION: True
    ATTNSHAPED_ACTIVATION: True
    ADJ_KEEP: False

    NORM: syncBN
    # PRETRAIN_PATH: '/mnt21t/home/mm2022/fast-reid/weights/lup_moco_r50.pth'
    # PRETRAIN_PATH: '/mnt21t/home/mm2022/fast-reid/weights/lupws_r50.pth'

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)
        
  HEADS:
    NORM: syncBN
    ATTN: 32

INPUT:
  AUTOAUG:
    ENABLED: False

  RPT:
    ENABLED: False

SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 64

  MAX_EPOCH: 160
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_NORM: 0.0005

  SCHED: MultiStepLR
  STEPS: [80, 120]
  GAMMA: 0.1
  
  DELAY_EPOCHS: 0
  ETA_MIN_LR: 1.0e-07
  FREEZE_ITERS: 0

  CHECKPOINT_PERIOD: 20

TEST:
  EVAL_PERIOD: 1
  IMS_PER_BATCH: 64
