_BASE_: ../Base-bagtricks.yml

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: logs/market1501/bagtricks_R50_LupNL

MODEL:
  BACKBONE:
    PRETRAIN_PATH: '/mnt21t/home/mm2022/fast-reid/weights/lupws_r50.pth'