_BASE_: ../Base-SBS.yml

DATASETS:
  NAMES: ("SynergyReID",)
  TESTS: ("SynergyReID",)

OUTPUT_DIR: logs/MDPR/Market1501/

MODEL:
  META_ARCHITECTURE: MDPR

  BACKBONE:
    WITH_IBN: True
    WITH_NL: False
    DEPTH: 101x
    PRETRAIN: True
    LAST_STRIDE: 1
    EMBEDDING_DIM: 512
    PRETRAIN_PATH: './weights/lup_moco_r101.pth'

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss")

    TRI:
      MARGIN: 0.05

INPUT:
  AUTOAUG:
    ENABLED: False
    PROB: 0.1

  RPT:
    ENABLED: True

  REA:
    ENABLED: True

  SIZE_TRAIN: [ 384, 192 ]

  SIZE_TEST: [ 384, 192 ]

SOLVER:
  AMP:
    ENABLED: True

  IMS_PER_BATCH: 64

  BASE_LR: 0.00035
  DELAY_EPOCHS: 0
  ETA_MIN_LR: 1.0e-07
  FREEZE_ITERS: 0

  CHECKPOINT_PERIOD: 60
  MAX_EPOCH: 40
  SCHED: CosineAnnealingLR
  WARMUP_ITERS: 200

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128